import org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener;
public class FunctionUse849 {
public void funcUse() {
OneTimeExecutionApplicationContextEventListener onetimeexecutionapplicationcontexteventlistener = new OneTimeExecutionApplicationContextEventListener();
onetimeexecutionapplicationcontexteventlistener.onApplicationEvent(null);
}
}