import org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener;
public class FunctionUse850 {
public void funcUse() {
OneTimeExecutionApplicationContextEventListener onetimeexecutionapplicationcontexteventlistener = new OneTimeExecutionApplicationContextEventListener();
onetimeexecutionapplicationcontexteventlistener.onApplicationContextEvent(null);
}
}